---
## Segmentation
video_input: 1              # Input Must be OpenCV readable
fps_interval: 5             # Interval [s] to print fps of the last interval in console
alpha: 0.5                  # mask overlay factor
bbox : True                 # compute boundingbox in postprocessing
minArea: 500                # min Pixel Area to apply bounding boxes (avoid noise)

## Testing
image_path: 'test_images'   # path for test.py test_images
cpu_only: False             # CPU Placement for speed test

## Model
model_name: 'deeplabv3_mnv2_pascal_train_aug_2018_01_29'
model_path: 'models/deeplabv3_mnv2_pascal_train_aug/frozen_inference_graph.pb'
download_base: 'http://download.tensorflow.org/models/'
